Don't propagate ALTER ROLE SET when scoped to a different database
citusdata/citus pull request #4471
Opened 2021-01-05 17:54 UTC by bergeron

Don't propagate ALTER ROLE SET when scoped to a different database.

Citus was propagating ` ALTER ROLE <my-role> IN DATABASE <my-db> ...` when `my-db` is not the database you're logged into.  This fails if `my-db` does not exist on all workers.  Since the current database doesn't know whether  `my-db` is a citus database with the same workers, I felt it should not propagate.

```
postgres=# ALTER ROLE brian IN DATABASE no_citus RESET ALL;
ERROR:  database "no_citus" does not exist
CONTEXT:  while executing command on pg3s-1.pg3s-svc.arc.svc.cluster.local:5432
```

2021-01-15 15:54 UTC, halilozanakgul requested changes

2021-01-15 15:54 UTC, halilozanakgul commented on src/backend/distributed/commands/role.c
>  	ObjectAddress address = GetObjectAddressFromParseTree(node, false);
Can you move the `if` statement above this line, so we don't calculate address unnecessarily.

2021-01-29 22:59 UTC, bergeron commented on src/test/regress/sql/alter_role_propagation.sql
> +SELECT run_command_on_workers($$SELECT json_agg(pg_db_role_setting) from pg_db_role_setting$$);
Thanks, updated

2021-02-01 10:58 UTC, halilozanakgul approved these changes

2021-02-01 12:48 UTC, hanefi approved these changes
Hello @bergeron and thanks for your contribution.

All changes here look ok.

It appears that one of our tests are failing due to an issue on our part. That's to be expected, and harmless.

2021-02-01 12:49 UTC, merged