Adds stackoverflow badge into README.md
citusdata/citus pull request #5589
Opened 2021-12-31 09:34 UTC by gurkanindibay

DESCRIPTION: Adds stackoverflow badge into README.md

2021-12-31 13:07 UTC, metdos requested changes

2021-12-31 13:22 UTC, gurkanindibay commented on README.md
> +<a href="https://stackoverflow.com/questions/tagged/citus">
I fixed formats similar to the previous ones

2021-12-31 13:27 UTC, metdos commented on README.md
> +[![Stack Overflow](https://img.shields.io/badge/Stack%20Overflow-%20-545353?logo=Stack%20Overflow)](https://stackoverflow.com/questions/tagged/citus)
Can we find a badge from the Stackoverflow website, we're not pulling any data via img.shields.io, do we need it?

2022-01-03 08:14 UTC, metdos commented on README.md
> +
Could you drop this extra line and squash commits?

2022-01-03 10:16 UTC, gurkanindibay commented on README.md
> +
Removed the extra line

2022-01-03 10:18 UTC, gurkanindibay commented on README.md
> +
@metdos Could you check and approve for me to be able to merge the PR

2022-01-03 10:40 UTC, metdos commented on README.md
> +
"squash commits?"

Could you do this first? I want to see only one commit.

2022-01-04 07:30 UTC, gurkanindibay commented on README.md
> +
Squashed as you suggested

2022-01-04 07:33 UTC, metdos commented
Looks good.

2022-01-04 07:34 UTC, metdos approved these changes

2022-01-04 07:42 UTC, merged