Fix upgrade paths for 11.0
citusdata/citus pull request #6171
Opened 2022-08-15 18:48 UTC by agedemenli

Fixing the upgrade path for version 11.0

2022-08-15 18:59 UTC, hanefi requested changes

2022-08-15 18:59 UTC, hanefi commented on src/backend/distributed/sql/downgrades/citus--10.2-5--10.2-4.sql
> +#include "../udfs/citus_finish_pg_upgrade/10.2-4.sql"
We already have the same file in the parent directory. I think we should remove this one.

2022-08-15 18:59 UTC, hanefi commented on src/test/regress/sql/multi_extension.sql
> +
I like these lines. However some of the next tests also need to be updated now. Please go over the occurrences of `10.2-4` later in the file and change them into `10.2-5` if it makes sense to you.

Some examples:

> -- Test downgrade to 10.2-4 from 11.0-1

> ALTER EXTENSION citus UPDATE TO '10.2-4';

2022-08-16 10:13 UTC, hanefi commented
One final comment, and we are good to go.

You renamed a file, but the comment in it became stale now. The comment does not match the file name.

https://github.com/citusdata/citus/blob/8bb0dee7f361d15fc884842551305fca7debf213/src/backend/distributed/sql/citus--10.2-5--11.0-1.sql#L1

I think you can continue working on the other branches after this fix is over. Let's try to merge 3 PRs after all of them are ready.

2022-08-16 10:15 UTC, agedemenli commented
> One final comment, and we are good to go.
> 
> You renamed a file, but the comment in it became stale now. The comment does not match the file name.
> 
> https://github.com/citusdata/citus/blob/8bb0dee7f361d15fc884842551305fca7debf213/src/backend/distributed/sql/citus--10.2-5--11.0-1.sql#L1
> 
> I think you can continue working on the other branches after this fix is over. Let's try to merge 3 PRs after all of them are ready.

Missed that, thank you!
Fixed now.
Will let you know when the other ones are ready as well

2022-08-16 10:17 UTC, hanefi approved these changes
Let's wait until the changes for `main` and `release-10.2` are ready.

We better squash the commits, and have a descriptive commit message.

2022-08-17 18:34 UTC, merged