Update Citus Technical Documentation about the rebalancer
citusdata/citus pull request #7638
Opened 2024-06-26 14:30 UTC by JelteF

The section about the rebalancer algorithm and the backround tasks were
empty.

2024-06-26 14:38 UTC, marcoslot commented on src/backend/distributed/README.md
> +clear the algorithm doesn't actually do andy shard group moves, it only does
```suggestion
clear the algorithm doesn't actually do any shard group moves, it only does
```

2024-06-26 14:38 UTC, marcoslot commented on src/backend/distributed/README.md
> +Ofcourse the devil is in the details though.
```suggestion
Of course, the devil is in the details though.
```

2024-06-26 14:38 UTC, marcoslot commented on src/backend/distributed/README.md
> +The algorithm is full of thresholds, the main reason these exists is because
```suggestion
The algorithm is full of thresholds, the main reason these exist is because
```

2024-06-26 14:50 UTC, marcoslot commented on src/backend/distributed/README.md
> +  necessarily problematic and might very well resolve automatically over time
```suggestion
  necessarily problematic and might very well resolve automatically over time. For example, consider a scenario in which
```

2024-06-27 02:32 UTC, steven-sheehy requested changes

2024-06-27 02:32 UTC, steven-sheehy commented on src/backend/distributed/README.md
> +optimimum, which so far has proved effective in getting to a pretty optimal
```suggestion
optimum, which so far has proved effective in getting to a pretty optimal
```

2024-06-27 02:32 UTC, steven-sheehy commented on src/backend/distributed/README.md
> +problem](https://en.wikipedia.org/wiki/Knapsack_problem). So instead going for
```suggestion
problem](https://en.wikipedia.org/wiki/Knapsack_problem). So instead of going for
```

2024-06-27 02:32 UTC, steven-sheehy commented on src/backend/distributed/README.md
> +Eventhough it won't result in the perfect balance, the  greedy aproach has two
```suggestion
Even though it won't result in the perfect balance, the  greedy approach has two
```

2024-06-27 02:32 UTC, steven-sheehy commented on src/backend/distributed/README.md
> +and that is "utilization". Utilization is total cost of all shard groups
```suggestion
and that is "utilization". Utilization is the total cost of all shard groups
```

2024-06-27 02:32 UTC, steven-sheehy commented on src/backend/distributed/README.md
> +1. Tasks can depend on eachother. This makes sure that one task doesn't start
```suggestion
1. Tasks can depend on each other. This makes sure that one task doesn't start
```

2024-06-27 12:32 UTC, onurctirtir approved these changes

2024-06-27 14:07 UTC, merged