Adds a method to determine if current node is primary
citusdata/citus pull request #7720
Opened 2024-11-01 21:42 UTC by xgerman

DESCRIPTION: PR description that will go into the change log, up to 78 characters

2025-03-10 13:01 UTC, onurctirtir commented on src/backend/distributed/sql/udfs/citus_is_primary_node/latest.sql
Also need to create src/backend/distributed/sql/udfs/citus_is_primary_node/12.2-1.sql by directly copying the contents of this file and need to include that file from the current versions's migration script, as in https://github.com/citusdata/citus/blob/main/CONTRIBUTING.md#making-sql-changes.

Also need to drop this function in the downgrade path.

2025-03-13 13:07 UTC, onurctirtir commented
Seems check-style is failing, will you be able to run "make reindent". If not, I can quickly do that.

Also, you can ignore the merge conflicts. They happen because we recently merged a big PR to main but I can take care of them too.

2025-03-13 16:00 UTC, xgerman commented
@onurctirtir  I ran `make reindent` but when I an `git diff` on the output it dn't find a difference. So it might be better if you run it since soemthing doesn't seem to work roght on my rig.

2025-03-14 15:23 UTC, onurctirtir approved these changes
Thanks for your contribution!

2025-03-14 16:07 UTC, onurctirtir requested changes
Oh wait, we at least need a few simple tests before merging.

2025-03-18 14:31 UTC, onurctirtir approved these changes
We can merge once the tests pass, thanks!

2025-03-18 15:12 UTC, merged